index:
    path: /
    controller: App\Controller\FrontController::index

home:
  path: /home
  controller: Symfony\Bundle\FrameworkBundle\Controller\RedirectController::redirectAction
  defaults:
    route: index
    permanent: true

mentions_legales:
  path: /mentions-legales
  controller: Symfony\Bundle\FrameworkBundle\Controller\TemplateController::templateAction
  defaults:
    template: static/mentionslegales.html.twig
